{% set name = "Routes" %}
{% set version = "1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc03d1a357cdb7af82e3909ee8ff93cb2b2afb48aca23bfde0117d6f49f624a7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six
    - repoze.lru >=0.3

test:
  imports:
    - routes

about:
  home: https://routes.readthedocs.io/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Routing Recognition and Generation Tools
  dev_url: https://github.com/bbangert/routes
  doc_url: https://routes.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
