travis:
  secure:
    BINSTAR_TOKEN: RyVHYuE6yyLNAEr+ORlXvEVrJSHrrpKDPB0Pq+D8Bwiu9djyQP9GKp2X5QnkAYCgtk6rHuCElAU7fW0QzTtJyfZOzSIlKLwq8LvEMCHmjxRU2+AYWPafvE9re5c673ESWGjZ4nViFleP6Gvj2fz9K35274L7ijDfa8E3Ls9vTk56LaVbp/OW1qtMl6pXne0H3fdBFcIknyswdwr3DpqfliKZOzD6gkOlrlmfGqm4Cw+MtxXdfl78x+yGRgUd2upvd8MBzgEu2BpNPjOdSEK88nhmHv7rEoW4Ag2t1CrWKMsUcfFHyo3J/oiesWUC6qAWrBLKwVG3wbSDI1SmHXOlmc/4sDANYbCHe4e/PuL5MI/B2is9nAHFhYb/5tHEeWYHnrAWeQ6ETTNge8B21hm8hhN2HY4F+0ppkrDR5pdeVYmliOVZhiqkvVP05imSISpOksgjor7pZtm6J6GUEYEh8fz99amVk95Sy+LB7dEILRlb7EyBCxQnHlLswpSScpe4a8eI5ixpW3Z5BveDhOYi+o7Rp0yqQSk+EtwLtPzzMHWX67JVx802hmbEsAFuAlF5eA9PpQEFTCfvqD1UI/cycsxwmhaflTTEmEWWpvVMMffK+REsE5EXWP5YyMeXVXERJxRdowUC/aCiv3ECwfnUnq0UAHdFseYUcVLatrMqCDc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
